spring:
  thymeleaf:
    #关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://8.138.161.55:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: seckill
    password: seckill
    # 数据库连接池
    hikari:
      #连接池名
      pool-name: Hsp_Hikari_Poll
      #最小空闲连接
      minimum-idle: 5
      #空闲连接存活最大时间，默认 60000(10 分钟)
      idle-timeout: 60000
      # 最大连接数，默认是 10
      maximum-pool-size: 10
      #从连接池返回来的连接自动提交
      auto-commit: true
      #连接最大存活时间。0 表示永久存活，默认 180000（30 分钟）
      max-lifetime: 180000
      #连接超时时间，默认 30000（30 秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: select 1

  redis:
#    cluster:
#      nodes:
#        - 192.168.252.133:6379
#        - 192.168.252.133:6380
#        - 192.168.252.133:6381
#        - 192.168.252.133:6389
#        - 192.168.252.133:6390
#        - 192.168.252.133:6391
#    host: 192.168.252.133

    host: 8.138.161.55
    port: 6379
    database: 0
    timeout: 10000ms
    jedis:
      pool:
        max-active: 24 #默认值一般为 cpu * 2
        max-wait: 10000ms
        min-idle: 0
        max-idle: 240
    password: 19971001
  rabbitmq:
    host: 8.138.161.55
    virtual-host: /
    username: law
    password: 19971001
    port: 5672 #web监控插件的端口是15672
    listener:
      simple:
        #消费者的最小数量
        concurrency: 10
        #消费者的最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息,处理之后才能继续下一条消息
        prefetch: 1
        #启动时是否默认启动mq容器
        auto-startup: true
        #被拒绝后，是否重新进入消息队列
        default-requeue-rejected: true
    #模板配置
    template:
      retry:
        #启动重试机制，默认false
        enabled: true
        #重试时间间隔
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1


#mybatis-plus 配置
mybatis-plus:
  #配置 mapper.xml 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置 mybatis 数据返回类型别名
  type-aliases-package: com.yeung.seckill.pojo

#mybatis sql 打印
logging:
  level:
    com.yeung.seckill.mapper: debug

